<a href="https://colab.research.google.com/github/nikatnguyen/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [2]:
# Drop the non-beneficial ID columns, 'EIN', 'NAME', 'AFFILIATION'
df = application_df.drop(columns=['EIN','NAME', 'AFFILIATION'])
df.head()


APPLICATION_TYPE CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0              T10          C1000    ProductDev   Association       1   
1               T3          C2000  Preservation  Co-operative       1   
2               T5          C3000    ProductDev   Association       1   
3               T3          C2000  Preservation         Trust       1   
4               T3          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [4]:
# Determine the number of unique values in each column.
df.nunique()

APPLICATION_TYPE            17
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
print(classification_count[classification_count > 1])

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64


In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_count[classification_count < 500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

In [12]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop(["IS_SUCCESSFUL"], axis='columns').values


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [13]:
print(X)

[[ 10520599         1      5000 ...         0         1         0]
 [ 10531628         1    108590 ...         0         1         0]
 [ 10547893         1      5000 ...         0         1         0]
 ...
 [996012607         1      5000 ...         0         1         0]
 [996015768         1      5000 ...         0         1         0]
 [996086871         1  36500179 ...         0         1         0]]


In [14]:
print(y)

[1 1 0 ... 0 1 0]


In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 20
hidden_nodes_layer4 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 80)                1569120   
                                                                 
 dense_1 (Dense)             (None, 30)                2430      
                                                                 
 dense_2 (Dense)             (None, 20)                620       
                                                                 
 dense_3 (Dense)             (None, 10)                210       
                                                                 
 dense_4 (Dense)             (None, 1)                 11        
                                                                 
Total params: 1572391 (6.00 MB)
Trainable params: 1572391 (6.00 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 10s 11ms/step - loss: 0.4774 - accuracy: 0.7715
Epoch 2/100
804/804 [==============================] - 9s 11ms/step - loss: 0.1946 - accuracy: 0.9211
Epoch 3/100
804/804 [==============================] - 8s 10ms/step - loss: 0.0995 - accuracy: 0.9609
Epoch 4/100
804/804 [==============================] - 8s 10ms/step - loss: 0.0938 - accuracy: 0.9619
Epoch 5/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0924 - accuracy: 0.9624
Epoch 6/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0918 - accuracy: 0.9629
Epoch 7/100
804/804 [==============================] - 8s 10ms/step - loss: 0.0905 - accuracy: 0.9628
Epoch 8/100
804/804 [==============================] - 8s 11ms/step - loss: 0.0899 - accuracy: 0.9626
Epoch 9/100
804/804 [==============================] - 9s 12ms/step - loss: 0.0897 - accuracy: 0.9636
Epoch 10/100
804/804 [==============================] - 8s 10ms/step - loss: 0.08

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.9111 - accuracy: 0.7012 - 1s/epoch - 4ms/step
Loss: 0.9111442565917969, Accuracy: 0.7012245059013367


ATTEMPT 2

In [20]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  100

nn2 = tf.keras.models.Sequential()

# First hidden layer
nn2.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Output layer
nn2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 100)               1961400   
                                                                 
 dense_6 (Dense)             (None, 1)                 101       
                                                                 
Total params: 1961501 (7.48 MB)
Trainable params: 1961501 (7.48 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
# Compile the model
nn2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [22]:
# Train the model
fit_model = nn2.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 10s 12ms/step - loss: 1.0662 - accuracy: 0.6630
Epoch 2/100
804/804 [==============================] - 9s 11ms/step - loss: 0.4738 - accuracy: 0.9021
Epoch 3/100
804/804 [==============================] - 9s 11ms/step - loss: 0.1641 - accuracy: 0.9562
Epoch 4/100
804/804 [==============================] - 9s 12ms/step - loss: 0.1334 - accuracy: 0.9598
Epoch 5/100
804/804 [==============================] - 9s 12ms/step - loss: 0.1196 - accuracy: 0.9609
Epoch 6/100
804/804 [==============================] - 10s 12ms/step - loss: 0.1122 - accuracy: 0.9614
Epoch 7/100
804/804 [==============================] - 10s 12ms/step - loss: 0.1079 - accuracy: 0.9617
Epoch 8/100
804/804 [==============================] - 10s 12ms/step - loss: 0.1047 - accuracy: 0.9618
Epoch 9/100
804/804 [==============================] - 9s 11ms/step - loss: 0.1029 - accuracy: 0.9624
Epoch 10/100
804/804 [==============================] - 21s 26ms/step - loss: 

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 1.0130 - accuracy: 0.7212 - 1s/epoch - 4ms/step
Loss: 1.0129706859588623, Accuracy: 0.72116619348526


ATTEMPT 3

In [24]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 20

nn3 = tf.keras.models.Sequential()

# First hidden layer
nn3.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

nn3.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

nn3.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 80)                1569120   
                                                                 
 dense_8 (Dense)             (None, 30)                2430      
                                                                 
 dense_9 (Dense)             (None, 20)                620       
                                                                 
 dense_10 (Dense)            (None, 1)                 21        
                                                                 
Total params: 1572191 (6.00 MB)
Trainable params: 1572191 (6.00 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
# Compile the model
nn3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [26]:
# Train the model
fit_model = nn3.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 10s 11ms/step - loss: 0.4760 - accuracy: 0.7724
Epoch 2/100
804/804 [==============================] - 9s 11ms/step - loss: 0.1237 - accuracy: 0.9550
Epoch 3/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0975 - accuracy: 0.9618
Epoch 4/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0936 - accuracy: 0.9621
Epoch 5/100
804/804 [==============================] - 8s 11ms/step - loss: 0.0924 - accuracy: 0.9618
Epoch 6/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0925 - accuracy: 0.9624
Epoch 7/100
804/804 [==============================] - 9s 11ms/step - loss: 0.0908 - accuracy: 0.9623
Epoch 8/100
804/804 [==============================] - 10s 12ms/step - loss: 0.0906 - accuracy: 0.9624
Epoch 9/100
804/804 [==============================] - 8s 11ms/step - loss: 0.0901 - accuracy: 0.9632
Epoch 10/100
804/804 [==============================] - 8s 10ms/step - loss: 0.0

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.8965 - accuracy: 0.6331 - 827ms/epoch - 3ms/step
Loss: 0.8964827656745911, Accuracy: 0.633119523525238


In [ ]:
# Export our model to HDF5 file
nn.save_weights('AlphabetSoupCharity.h5')
nn2.save_weights('AlphabetSoupCharity2.h5')
nn2.save_weights('AlphabetSoupCharity3.h5')